"""One-off universe refresher.

Fetches up-to-date tickers for common US indexes from public sources and
writes them into `agent/data/*.csv`. Run when you want to expand or
refresh the screening universe.

Usage:
    python scripts/refresh_universes.py              # refresh all
    python scripts/refresh_universes.py sp500        # refresh one
    python scripts/refresh_universes.py russell1000  # creates the file if missing

Sources:
    S&P 500:      Wikipedia "List of S&P 500 companies" (first sortable table)
    Nasdaq 100:   Wikipedia "Nasdaq-100" (components table)
    Russell 1000: Wikipedia "Russell 1000 Index" (components table, large)

Wikipedia tables move around; if a fetch starts returning 0 rows, open the
page in a browser and update the selector below.
"""
from __future__ import annotations

import sys
from pathlib import Path

import httpx
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "agent" / "data"

SOURCES = {
    "sp500": ("https://en.wikipedia.org/wiki/List_of_S%26P_500_companies", 0, "Symbol"),
    "nasdaq100": ("https://en.wikipedia.org/wiki/Nasdaq-100", 4, "Ticker"),
    "russell1000": ("https://en.wikipedia.org/wiki/Russell_1000_Index", 2, "Ticker"),
}


def fetch(name: str) -> list[str]:
    url, table_idx, col = SOURCES[name]
    html = httpx.get(url, headers={"User-Agent": "stockagent/1.0"}, timeout=30).text
    tables = pd.read_html(html)
    df = tables[table_idx]
    # Column name often drifts between pages; fall back to first column.
    if col in df.columns:
        syms = df[col].astype(str).tolist()
    else:
        syms = df.iloc[:, 0].astype(str).tolist()
    # Yahoo uses `-` where Wikipedia uses `.` (BRK.B -> BRK-B).
    syms = [s.strip().replace(".", "-").upper() for s in syms if s and s != "nan"]
    return sorted(set(syms))


def write(name: str, tickers: list[str]) -> None:
    p = OUT / f"{name}.csv"
    header = f"# {name.upper()} — auto-generated by scripts/refresh_universes.py. One ticker per line.\n"
    p.write_text(header + "\n".join(tickers) + "\n", encoding="utf-8")
    print(f"wrote {p} ({len(tickers)} tickers)")


def main() -> int:
    targets = sys.argv[1:] or list(SOURCES.keys())
    for name in targets:
        if name not in SOURCES:
            print(f"unknown universe: {name}; known: {list(SOURCES)}", file=sys.stderr)
            return 2
        try:
            tickers = fetch(name)
            if not tickers:
                print(f"{name}: 0 rows — Wikipedia layout may have changed", file=sys.stderr)
                continue
            write(name, tickers)
        except Exception as e:
            print(f"{name}: {e}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
